version: '3'

services:
  influxdb:
    image: influxdb:2.6-alpine
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      # Environment variables for influxdb
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=SKom
      - DOCKER_INFLUXDB_INIT_BUCKET=coolify
      - DOCKER_INFLUXDB_INIT_RETENTION=4d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
  telegraf:
    image: telegraf:1.25-alpine
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      # Environment variables for telegraf
      - DOCKER_INFLUXDB_INIT_HOST=http://influxdb:8086
      - DOCKER_INFLUXDB_INIT_ORG=SKom
      - DOCKER_INFLUXDB_INIT_BUCKET=coolify
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
  grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - 3000:80

volumes:
  grafana-storage:
  influxdbv2:
